name: CI for Java and Arduino

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install Arduino AVR platform
        run: arduino-cli core install arduino:avr

      - name: Run PowerShell CI Script
        run: |
          pwsh -File .github/scripts/localCI.ps1 -ComPort "" -BaudRate ""
        shell: pwsh

      - name: Upload deploy directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-folder
          path: deploy