name: CI for Java and Arduino

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install Arduino AVR platform
        run: arduino-cli core install arduino:avr

      - name: Install Doxygen
        run: |
          # Перевіряємо, чи є Doxygen в системному шляху
          if (-not (Get-Command doxygen -ErrorAction SilentlyContinue)) {
          Write-Host "Doxygen не знайдений. Встановлюємо Doxygen..."
          # Завантаження Doxygen з офіційного джерела
          Invoke-WebRequest -Uri https://github.com/doxygen/doxygen/releases/download/rel-1.12.0/doxygen-1.12.0-setup.exe -OutFile "doxygen-setup.exe"
          # Інсталяція Doxygen
          Start-Process -FilePath "doxygen-setup.exe" -ArgumentList "/S" -Wait
          # Додаємо шлях до Doxygen у змінну середовища PATH
          $env:PATH += ";C:\Program Files\doxygen\bin"
          } else {
          Write-Host "Doxygen вже встановлений."
          }

      - name: Run PowerShell CI Script
        run: |
          pwsh -File .github/scripts/localCI.ps1 -ComPort "" -BaudRate ""
        shell: pwsh

      - name: Upload deploy directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-folder
          path: deploy