name: CI for Java and Arduino

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install Arduino AVR platform
        run: arduino-cli core install arduino:avr

      - name: Install Doxygen
        run: |
          $DoxygenUrl = "https://doxygen.nl/files/doxygen-1.12.0.win64.exe"
          $DoxygenInstaller = "$env:Temp\doxygen_installer.exe"

          # Завантажити інсталятор
          Invoke-WebRequest -Uri $DoxygenUrl -OutFile $DoxygenInstaller

          # Інсталювати Doxygen
          Start-Process -FilePath $DoxygenInstaller -ArgumentList "/S" -Wait

          # Додати Doxygen до PATH
          $env:PATH += ";C:\Program Files\doxygen\bin"

      - name: Run PowerShell CI Script
        run: |
          pwsh -File .github/scripts/localCI.ps1 -ComPort "" -BaudRate ""
        shell: pwsh

      - name: Upload deploy directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-folder
          path: deploy
