name: CI for Java and Arduino

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  java:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean compile -B
        working-directory: client/RPS-client

      - name: Package JAR
        run: mvn package
        working-directory: client/RPS-client

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-app
          path: client/RPS-client/target/*.jar

  arduino:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'

      - name: Install Arduino AVR platform
        run: arduino-cli core install arduino:avr

      - name: Build Arduino Project
        run: |
          arduino-cli compile --fqbn arduino:avr:uno server/RPS-server/RPS-server.ino

      - name: Upload Arduino Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arduino-build
          path: server/RPS-server/build/*